import type { Metadata } from "next";

import "@/styles/reset.css";
import "@/styles/global.css";

import { Noto_Sans_JP, Space_Mono } from "next/font/google";
import clsx from "clsx";
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx(noto_sans_jp.variable, space_mono.variable)}>
        {children}
      </body>
    </html>
  );
}

const noto_sans_jp = Noto_Sans_JP({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-noto_sans_jp",
});

const space_mono = Space_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-space_mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
